### ISSUE TITLE
Did we intentionally make the frontend font size bigger ?

### ISSUE THREAD

**Issue by verdan** [lyft/amundsenfrontendlibrary#83]
**Before**
<img width="800" alt="Screen Shot 2019-04-16 at 4 55 05 PM" src="https://user-images.githubusercontent.com/25360476/56220304-8245f980-6068-11e9-9bcf-182cbc78f9ee.png">

**After**
<img width="800" alt="Screen Shot 2019-04-16 at 4 35 38 PM" src="https://user-images.githubusercontent.com/25360476/56220303-81ad6300-6068-11e9-9e68-76cb4d5795ac.png">

@jinhyukchang

**Comment by jinhyukchang** [comment]
Hey @verdan ,
I believe this was part of UI improvement happened recently, but it seems like open sourced version does not show well as it's using different font.

@danwom Could you take a look?

**Comment by jinhyukchang** [comment]
Ref PR: https://github.com/lyft/amundsenfrontendlibrary/pull/57

**Comment by feng-tao** [comment]
@danwom could you take a look? I believe it is related to the UI revamp work.

**Comment by danwom** [comment]
Yes, all of these sizing and spacing changes were intentional. These are more in line with specs produced by our design team. We also produced designs specs (fonts, colors, etc) specifically for the OSS version recently but haven't had a chance to work on it. I realize these specs are not available to the public but I wonder what's the right format and place to share them.

I'll spend some time to polish OSS design this week, or once we figure out the right place to share design specs, someone from the community can work on it.

The fonts and colors are different in the OSS version, but do not cause significant deviation.
